### ISSUE TITLE
Project not in npm repository & license

### ISSUE THREAD

**Issue by pkopac** [MadKudu/node-marketo#10]
Hello!

Your project seems cool and just what I need, but I couldn't find it on npm: https://www.npmjs.com/search?q=marketo
There are only other (SOAP) projects. As there are no special instructions on installation, this might be some error.

Also, what's the license? Without any, it's "all rights reserved", I believe.

Thank you for resolving this issue!

**Comment by peaches** [comment]
Sorry for the slow response, we were having a discussion internally regarding the license and should have it updated shortly.

We haven't added the project to npm since it isn't quite complete yet, a few more APIs implemented and we will do so. Thanks for your interest though.

**Comment by pkopac** [comment]
Thank you! The licence is pretty important, otherwise it can't be legally used at all.

After adding this issue I noticed there was another one a week before me, so I kind of duplicated that unintentionally, also I found out the temporary solution is to add to dependencies as a link to git + commit hash.

**Comment by peaches** [comment]
Right, you should be able to specify the tagged version as well:

```
"node-marketo": "git+https://github.com/usermindinc/node-marketo.git#v0.3.0"
```

The license we're going forward with will be Apache 2.0. Hope that works for you.

**Comment by pkopac** [comment]
Yes, that is great. Thanks for the advice!

**Comment by pcothenet** [comment]
Now published to npm as `node-marketo-rest`. README updated accordingly.
