### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by yuanzhaoYZ** [MadKudu/node-marketo#24]
Greetings!
This is Yuan. I would like to take ownership of this repo. Would you mind transferring the ownership of this repo to me ?

Thanks,
Regards,

Yuan

**Comment by umcodemonkey** [comment]
Will do. Thanks for stepping up!

**Comment by umcodemonkey** [comment]
You appear to already have a fork of the repo in your account. You'll need to delete your fork before I can do the transfer.

**Comment by pcothenet** [comment]
Hi @umcodemonkey, I work with @yuanzhaoYZ at [MadKudu](http://www.madkudu.com). Can you transfer the repo to our organization account: https://github.com/MadKudu ?

We will merge Yuan's fork later. Thanks!

Paul

**Comment by umcodemonkey** [comment]
Github will not allow me to transfer to an organization I don't have admin rights to. Your team will need to pick a user account with admin rights to your org to accept the transfer, and then you can move it where you wish. I had to move it out of our own organization as a first step, as well.

**Comment by pcothenet** [comment]
OK. My account then: https://github.com/pcothenet

Thanks!

**Comment by umcodemonkey** [comment]
Similar to @yuanzhaoYZ, you already have a fork of this repository on your account. I cannot transfer ownership to you until it is deleted or renamed.

**Comment by pcothenet** [comment]
Oh my, sorry for the back and forth. Repo deleted, can you please try again?

**Comment by umcodemonkey** [comment]
Requested, you will need to now approve the transfer.
