### ISSUE TITLE
log.info while authentication error

### ISSUE THREAD

**Issue by FabriceGaudin** [MadKudu/node-marketo#37]
Why is `log.info` called when there's an authentication error ? It should throw an Error, I'm facing several issues because of this.
https://github.com/MadKudu/node-marketo/blob/master/lib/connection.js#L135

Btw, `e[0]` is undefined (it logs `"Unable to authenticate:  undefined"`)

**Comment by pcothenet** [comment]
Good point. I see no reason why it should log that error and not throw anything. 

I see that you guys already have a fork of your own. Do you want to do a quick fix and submit a PR? (otherwise I might be able to take a look at this later this week).

**Comment by FabriceGaudin** [comment]
@pcothenet No problem: https://github.com/MadKudu/node-marketo/pull/38

**Comment by pcothenet** [comment]
Awesome, thank you. Published to npm as `0.3.4`.

**Comment by FabriceGaudin** [comment]
@pcothenet Thank you !
