### ISSUE TITLE
This package depends on a vulnerable version of qs

### ISSUE THREAD

**Issue by sjparkinson** [MadKudu/node-marketo#66]
Snyk is reporting an issue with the qs package that is bundled with this package via:

```
node-marketo-rest@0.7.5 › restler@3.4.0 › qs@1.2.0
```

https://app.snyk.io/vuln/npm:qs:20170213

This packages uses restler, an unmaintained HTTP client that pins it's dependencies.

https://github.com/MadKudu/node-marketo/blob/94fa0bdcbc3f10fc6b8502001843b4783b62fd88/package.json#L22

[`restler/package.json`](https://github.com/danwrong/restler/blob/f31e457eaedb54def4a5e3fc84b3a161be0889e0/package.json#L30-L35)

```json
  "dependencies": {
    "qs": "1.2.0",
    "xml2js": "0.4.0",
    "yaml": "0.2.3",
    "iconv-lite": "0.2.11"
  },
```

I would suggest moving to an actively maintained package like [node-fetch](https://www.npmjs.com/package/node-fetch) or [request](https://www.npmjs.com/package/request).

**Comment by evantahler** [comment]
Are there any plans to update this?  @sjparkinson do you have a fork with this patched?

**Comment by bleonard** [comment]
Taking a shot at it with https://github.com/MadKudu/node-marketo/pull/81.
