### ISSUE TITLE
Error happens when webpack tries to build source when smartlist feature is being used

### ISSUE THREAD

**Issue by jsec516** [MadKudu/node-marketo#69]
webpack not able to build because of `node-marketo-rest` internal code when `smartlist` api being used.

ERROR in ./node_modules/node-marketo-rest/lib/marketo.js
Module not found: Error: Can't resolve './api/smartlist' in .../marketo-list/node_modules/node-marketo-rest/lib'
 @ ./node_modules/node-marketo-rest/lib/marketo.js 11:16-42
 @ ./node_modules/node-marketo-rest/index.js
 @ ./index.ts

**Comment by pcothenet** [comment]
Thanks for the issue and the fix. Published
